### ISSUE TITLE
Unable to create/load workspace

### ISSUE THREAD

**Issue by Matteas-Eden** [TheGuardianWolf/Annotation-Tool#1]
When attempting to create a directory, I receive the following error:
```
_type.scss:86TypeError: Cannot read property 'forEach' of undefined
    at Function.Video.parse (file:///C:/Program%20Files%20(x86)/AnnotationTool-win32-ia32/resources/app/app.bundle.js:1156:22)
    at file:///C:/Program%20Files%20(x86)/AnnotationTool-win32-ia32/resources/app/app.bundle.js:933:44
    at _fulfilled (file:///C:/Program%20Files%20(x86)/AnnotationTool-win32-ia32/resources/app/vendor.bundle.js:79597:55)
    at self.promiseDispatch.done (file:///C:/Program%20Files%20(x86)/AnnotationTool-win32-ia32/resources/app/vendor.bundle.js:79626:31)
    at Promise.promise.promiseDispatch (file:///C:/Program%20Files%20(x86)/AnnotationTool-win32-ia32/resources/app/vendor.bundle.js:79559:14)
    at file:///C:/Program%20Files%20(x86)/AnnotationTool-win32-ia32/resources/app/vendor.bundle.js:79367:45
    at runSingle (file:///C:/Program%20Files%20(x86)/AnnotationTool-win32-ia32/resources/app/vendor.bundle.js:78900:14)
    at flush (file:///C:/Program%20Files%20(x86)/AnnotationTool-win32-ia32/resources/app/vendor.bundle.js:78888:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ _type.scss:86
_type.scss:86 No images in directory.(anonymous function) @ _type.scss:86_rejected @ q.js:844(anonymous function) @ q.js:870when @ q.js:1122Promise.promise.promiseDispatch @ q.js:788(anonymous function) @ q.js:604runSingle @ q.js:137flush @ q.js:125_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```
The workspace directory is 'videos', where the video file is 'videos/video.mp4' and the annotation file is 'videos/workspace.json'. The json file appears to be generated correctly.
Then, attempting to load the workspace with the same directory and annotation file presents the following error:
``No images in directory``
The general instructions seem to imply that the frames will be extracted automatically, but that doesn't seem to be happening here. 
Luckily, I have the extracted frames of the video I want to annotate, so I put them in the same directory, but no luck. However, this brings about the first error.
Not really sure what to do, is there something I'm missing?

**Comment by TheGuardianWolf** [comment]
It's been a while since I last looked at this, I'll have a look when I'm done with work this evening.

**Comment by TheGuardianWolf** [comment]
Alright, I see what the issue is - the naming of the files do matter as I've hard coded a naming convention into the program.

I would advise downloading the samples.tar from the releases so that you have an idea of what the program expects for input as there are further items such as the calibration xml files that are required if you wanted to use the automatic inference.

```SX_Name_XXX_CX```

"X" is an integer, whereas "Name" is a string.

This is the current naming convention, the file here will give you some idea of how it is parsed.

https://github.com/TheGuardianWolf/Annotation-Tool/blob/master/src/app/shared/workspace/workspace.service.ts

```
    private getVideoContext() {
        let videoBasename = path.parse(this.videoFile).name.split('_');
        let sequenceNumber = parseInt(videoBasename[0].substr(-1));
        let sequenceName = videoBasename[1];
        let videoIncrement = videoBasename[2];
        let videoCamera = parseInt(videoBasename[3].substr(-1));

        this.annotation.data.number = sequenceNumber;
        this.annotation.data.name = sequenceName;
        this.annotation.data.increment = videoIncrement;
        this.annotation.data.camera = videoCamera;
    }
```

This tool was developed in two weeks with something very specific in mind, so I never got around to adding in error messages etc.

I will probably write a few more instructions/warnings to cover this issue.

**Comment by Matteas-Eden** [comment]
That's good to know that the naming convention was hardcode, but I was actually already using a file that follows it. When I said 'video/video.mp4' earlier, that was just an example. 
The video I've attempted to open (taken from samples.tar) is S1_Walk_003_C1.mp4. I've copied it into its own directory and added a blank json file. I also copied over all the calibration files since you mentioned them. I even mirrored the layout of 'samples' so that the file structure looks like this:
```
MyWorkspace/
    videos/
        S1_Walk_003_C1.mp4
    annotations/
        workspace.json
    calibration/
        <Calibration files>
```
Unfortunately, I still receive the same errors and can't load up the workspace.

**Comment by TheGuardianWolf** [comment]
Could you try not selecting the json file? 

Also I'm not sure if this affects it, but the workspace I used was always an empty folder.

I don't remember what the functionality for that json selection was for the workspace creation, but the json file expected should be one that is created from the app in the first place. The workspace can be created without anything in that json file selection box.

I was able to successfully create the workspace last night, so if not this, then the platform and environment may be required to debug further.

**Comment by Matteas-Eden** [comment]
I created a new folder, 'MyOtherWorkspace' which is empty.
I attempted to create a workspace selecting that folder and using the video from before. (I didn't put the video in the directory). I did not specify an annotation file.
I received this error:
```
ZoneAwareError__zone_symbol__error: Error: Command failed: C:\Program Files (x86)\AnnotationTool-win32-ia32\resources\app\native\CameraTool -E C:\Users\Matteas\Downloads\Summer Research 2018-2019\samples\videos\S1_Walk_003_C1.mp4 C:\Users\Matteas\Downloads\Summer Research 2018-2019\MyOtherWorkspace
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.



    at new Error (native)
    at ChildProcess.exithandler (child_process.js:218:12) [<root>]
    at emitTwo (events.js:106:13) [<root>]
    at ChildProcess.emit (events.js:191:7) [<root>]
    at maybeClose (internal/child_process.js:877:16) [<root>]
    at Socket.<anonymous> (internal/child_process.js:334:11) [<root>]
    at emitOne (events.js:96:13) [<root>]
    at Socket.emit (events.js:188:7) [<root>]
    at Pipe._handle.close [as _onclose] (net.js:493:12) [<root>]__zone_symbol__stack: "Error: Command failed: C:\Program Files (x86)\AnnotationTool-win32-ia32\resources\app\native\CameraTool -E C:\Users\Matteas\Downloads\Summer Research 2018-2019\samples\videos\S1_Walk_003_C1.mp4 C:\Users\Matteas\Downloads\Summer Research 2018-2019\MyOtherWorkspace↵'C:\Program' is not recognized as an internal or external command,
↵operable program or batch file.
↵↵    at new Error (native)↵    at ChildProcess.exithandler (child_process.js:218:12) [<root>]↵    at emitTwo (events.js:106:13) [<root>]↵    at ChildProcess.emit (events.js:191:7) [<root>]↵    at maybeClose (internal/child_process.js:877:16) [<root>]↵    at Socket.<anonymous> (internal/child_process.js:334:11) [<root>]↵    at emitOne (events.js:96:13) [<root>]↵    at Socket.emit (events.js:188:7) [<root>]↵    at Pipe._handle.close [as _onclose] (net.js:493:12) [<root>]"cmd: "C:\Program Files (x86)\AnnotationTool-win32-ia32\resources\app\native\CameraTool -E C:\Users\Matteas\Downloads\Summer Research 2018-2019\samples\videos\S1_Walk_003_C1.mp4 C:\Users\Matteas\Downloads\Summer Research 2018-2019\MyOtherWorkspace"code: 1killed: falsemessage: (...)get message: ()set message: (value)name: (...)get name: ()set name: (value)originalStack: (...)get originalStack: ()set originalStack: (value)signal: nullstack: (...)get stack: ()set stack: (value)toSource: ()toString: ()zoneAwareStack: (...)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: Object(anonymous function) @ _type.scss:86
_type.scss:86 No images in directory.(anonymous function) @ _type.scss:86_rejected @ q.js:844(anonymous function) @ q.js:870when @ q.js:1122Promise.promise.promiseDispatch @ q.js:788(anonymous function) @ q.js:604runSingle @ q.js:137flush @ q.js:125_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```
Despite the error, the 'workspace.json' file was created.
Attempting to load the workspace raises the same error from earlier ``No images in directory``.

I'm using 1.30 on Windows 10.

**Comment by TheGuardianWolf** [comment]
For that error, you will just need to move the tool to a place that does not include spaces in its path.

I can patch the code to fix it later but creating a release will take a bit.
________________________________

**Comment by Matteas-Eden** [comment]
So I moved it from Program Files (x86) to my Downloads folder (so now it doesn't have any spaces in the path) but I still get the error ``No images in directory``.

The error appears to be thrown at line 6 of _background-variant.scss:
``background-color:$color``

**Comment by TheGuardianWolf** [comment]
Did the create workspace option produce the extracted frames?

**Comment by Matteas-Eden** [comment]
No, it just gives the same error as 'load workspace'.

**Comment by TheGuardianWolf** [comment]
```C:\Program Files (x86)\AnnotationTool-win32-ia32\resources\app\native\CameraTool -E C:\Users\Matteas\Downloads\Summer Research 2018-2019\samples\videos\S1_Walk_003_C1.mp4 C:\Users\Matteas\Downloads\Summer Research 2018-2019\MyOtherWorkspace```

Could you please run this command manually using cmd (adjust paths to point to new folders). 

I suspect the frames are not being read as they also require specific naming that's produced by this tool.

However I'm not confident that the tool is working in your environment, this test should give me an indication of what is going on.

**Comment by TheGuardianWolf** [comment]
Also if you are working at UoA, I'm pretty close by and I can assist in person.

**Comment by Matteas-Eden** [comment]
After changing to the right directory, I ran
``CameraTool.exe -E C:\Users\Matteas\Downloads\Summer Research 2018-2019\samples\videos\S1_Walk_003_C1.mp4 C:\Users\Matteas\Downloads\Summer Research 2018-2019\MyOtherWorkspace``

It gave this: ``warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:578)``

[REDACTED]

**Comment by TheGuardianWolf** [comment]
I think that error is present due to a cygwin dependency. Unfortunately I have no easy way of testing as I don't have access to another Windows device.

Can you send me an email at jfan082 at aucklanduni.ac.nz and I'll see if I can't arrange a time to meet. I only have weekends available though.

Alternatively you could try Linux, it's easier to manage dependencies there.
________________________________

**Comment by Matteas-Eden** [comment]
Add zone documentation

**Comment by TheGuardianWolf** [comment]
Paths with spaces issue fixed, and documentation for creating the zones are in the samples archive.
